title: Andrew Ritchey # your name (or website title) here
logo: "/images/fadeghibliedit.png?raw=true" # your photo (or logo) here
description: > 
  🌲 Data druid and biostats bard.
  <br><br>
  📊 Brewing up machine learning magic every day.
  <br><br>
  <a href="https://www.linkedin.com/in/andrew-ritchey/">LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0
